alias cde='cd ~/work/tw/cde/'
alias cdeweb='cd ~/work/tw/cde/Corndog'
alias cdeios='cd ~/work/tw/cde/dealermatch_ios'
alias cdekbb='cd ~/work/tw/cde/kbb_service'
alias bcan='cd ~/work/projects/blankcanvas'
alias be='bundle exec'
alias bec='bundle exec cucumber'
alias ber='bundle exec rspec'